name: Publish Docker

on:
  workflow_call:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_and_publish_platform_containers:
    name: Build and publish platform containers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Build the docker image
        env:
          BUILD_PLATFORM: 'amd64'
        run: |
          APP_VERSION="$(git name-rev --tags --name-only $(git rev-parse HEAD) | head -n 1 | sed 's/\^0//')"
          GIT_SHA="$(git rev-parse HEAD)"

          docker build \
            -f ./docker/Dockerfile \
            --progress=plain \
            -t "documenso/documenso-$BUILD_PLATFORM:latest" \
            .
